AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: React Custom SSR function for serverless deployment

Resources:
  ReactSsrApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      AlwaysDeploy: true

  SsrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Description: 'React Custom SSR Handler'
      MemorySize: 4096
      Timeout: 30
      Handler: build/serverless.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: ReactSsrApi
      Environment:
        Variables:
          NODE_ENV: production

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ReactSsrApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"